name: CI

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - uses: actions/checkout@v3

      - name: 'Set up Oracle JDK 19'
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 20
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Rename target
        run: mv target/*.jar target/QQBot.jar
      - name: Upload to server
        uses: easingthemes/ssh-deploy@main
        env:
          ARGS: '-avz --delete'
          SOURCE: 'target/QQBot.jar'
          TARGET: '/home/ubuntu/qqbot'
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ubuntu
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_ACCESS_KEY }}
      - name: Restart Docker
        uses: appleboy/ssh-action@v0.1.4
        with:
          key: ${{ secrets.SERVER_ACCESS_KEY }}
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu
          script_stop: true
          script: |
            docker stop qqbot
            docker rm qqbot
            docker rmi yumoyumoyumo/qqbot:1.0
            docker build -t yumoyumoyumo/qqbot:1.0 /home/ubuntu/qqbot/
            docker run -d -p 8088:8088 --name qqbot yumoyumoyumo/qqbot:1.0